karyotype = kariotype_SNV.txt
<<include ideogram.conf>>

<plots>

<plot>
type=text
color=black
label_font=default
label_size=42p

file=gene_name.txt

r0=1r
r1=1.3r
padding=2p
rpadding=2p

show_links=yes
link_dims	=6p
link_thickness=2p
link_color=red
label_snuggle=yes
max_snuggle_distance=2r
snuggle_tolerance=0.5
snuggle_sampling=2
</plot>

<plot>
type	=line
#max_gap=1u
file=gal_all_reg_snp.txt
color=vvdred
min=0
max=430
r0=0.895r
r1=0.995r
thickness=3

<axes>
<axis>
spacing=0.05r
color=lgrey
thickness=1

</axis>
</axes>

</plot>

<plot>
type	=scatter
#max_gap=1u
file=gal_all_reg_snp.txt
color=vvdred
min=0
max=430
r0=0.895r
r1=0.995r


glyph=circle
glyph_size=20
color=vvdred
stroke_color=dred
stroke_thickness=1

</plot>

</plots>

<image>
<<include etc/image.conf>>
</image>

<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>
        